version: '3.8'

services:
  # server:
  #   image: revchenkov/compvis-test_solution:v0.3_camera_arm64_b
  #   build:
  #     context: camera/
  #     dockerfile: Dockerfile
  #   runtime: nvidia
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   volumes:
  #      - /dev/video0:/dev/video0:ro
  #      - /tmp/argus_socket:/tmp/argus_socket
  #      - /home/user/compvis/UAV_Docker/test-solution/container_output:/app/container_output
  #   ports:
  #     - "9000:9000"
  #   restart: always
  #   privileged: true

  client:
    image: revchenkov/compvis-test_solution:v0.3_client_arm64_b
    build:
      context: test-solution
      dockerfile: Dockerfile_jet
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
       - /dev/video0:/dev/video0:ro
       - /tmp/argus_socket:/tmp/argus_socket
       - /home/user/compvis/UAV_Docker/test-solution/container_output:/app/container_output
    privileged: true
    # depends_on:
    #   - server
