FROM ultralytics/ultralytics:latest-jetson-jetpack6 

RUN apt-get update && apt-get install libx264-dev

RUN python3 -m pip install --upgrade pip

RUN pip install dill

WORKDIR /app

COPY requirements.txt /app/

RUN pip install -r requirements.txt

COPY benchmark.py best_pep.pt best.pt Fire_Detection.py Human_Detection.py solution.py test_scv.py bench.mp4 test.py /app/

RUN mkdir container_output

CMD ["python3", "/app/test.py"]