FROM small_ult:latest

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --use-pep517 -r requirements.txt

COPY test.py new_detection_for_image.py best_yolo11.pt best.pt Fire_Detection.py Human_Detection.py bench3.mp4 /app/

RUN mkdir container_output

CMD ["python3", "/app/new_detection_for_image.py"]