FROM ultralytics/ultralytics:latest-jetson-jetpack6 

RUN apt-get update && apt-get install libx264-dev

RUN python3 -m pip install --upgrade pip

RUN pip install dill

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --use-pep517 -r requirements.txt

COPY test.py new_detection_for_image.py benchmark.py best_yolo11.pt best.pt best_pep.pt Fire_Detection.py Human_Detection.py Human_Detection_vid.py bench3.mp4 /app/

RUN mkdir container_output

CMD ["python3", "/app/new_detection_for_image.py"]