version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=0
    volumes:
      - /d/Coding/AI/UAV/camera_input:/app/camera_input:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "9000:9000"
    network_mode: "host"
    restart: always
    privileged: true